---
# this is installed with clamav on ubuntu
#
- name: install clamav updater package 
  dnf:
    name: 
    - clamav-update
  when: ansible_pkg_mgr == 'dnf'


- name: update freshclam database owner config 
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?DatabaseOwner\s+.+'
    line: "DatabaseOwner {{ clamav_freshclam_databaseowner }}"

- name: update freshclam update log file config
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?UpdateLogFile\s+.+'
    line: "UpdateLogFile {{ clamav_freshclam_updatelogfile }}"

- name: update freshclam log verbose config
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?LogVerbose\s+.+'
    line: "LogVerbose {{ clamav_freshclam_logverbose }}"

- name: update freshclam log syslog config
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?LogSyslog\s+.+'
    line: "LogSyslog {{ clamav_freshclam_logsyslog }}"

- name: update freshclam log facility config
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?LogFacility\s+.+'
    line: "LogFacility {{ clamav_freshclam_logfacility }}"

- name: update freshclam log file max size config
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?LogFileMaxSize\s+.+'
    line: "LogFileMaxSize {{ clamav_freshclam_logfilemaxsize }}"

- name: update freshclam log rotate config
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?LogRotate\s+.+'
    line: "LogRotate {{ clamav_freshclam_logrotate }}"

- name: update freshclam log time config
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?LogTime\s+.+'
    line: "LogTime {{ clamav_freshclam_logtime }}"

- name: update freshclam foreground
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?Foreground\s+.+'
    line: "Foreground {{ clamav_freshclam_foreground }}"

- name: update freshclam debug
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?Debug\s+.+'
    line: "Debug {{ clamav_freshclam_debug }}"

- name: update freshclam Max Attempts
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?MaxAttempts\s+.+'
    line: "MaxAttempts {{ clamav_freshclam_maxattempts }}"

- name: update freshclam database directory
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?DatabaseDirectory\s+.+'
    line: "DatabaseDirectory {{ clamav_freshclam_databasedirectory }}"

- name: update freshclam dns database info
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?DNSDatabaseInfo\s+.+'
    line: "DNSDatabaseInfo {{ clamav_freshclam_dnsdatabaseinfo }}"

- name: update freshclam connect timeout
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?ConnectTimeout\s+.+'
    line: "ConnectTimeout {{ clamav_freshclam_connecttimeout }}"

- name: update freshclam receive timeout
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?ReceiveTimeout\s+.+'
    line: "ReceiveTimeout {{ clamav_freshclam_receivetimeout }}"

- name: update freshclam test databases
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?TestDatabases\s+.+'
    line: "TestDatabases {{ clamav_freshclam_testdatabases }}"

- name: update freshclam scripted updates
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?ScriptedUpdates\s+.+'
    line: "ScriptedUpdates {{ clamav_freshclam_scriptedupdates }}"

- name: update freshclam compress local database
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?CompressLocalDatabase\s+.+'
    line: "CompressLocalDatabase {{ clamav_freshclam_compresslocaldatabase }}"

- name: update freshclam bytecode
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?Bytecode\s+.+'
    line: "Bytecode {{ clamav_freshclam_bytecode }}"

- name: update freshclam notify clamd
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?NotifyClamd\s+.+'
    line: "NotifyClamd {{ clamav_freshclam_notifyclamd }}"

#TODO figure out how to do these two plays in one step
- name: clear out freshclam database mirror
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: DatabaseMirror\s+.+
    state: absent

- name: add freshclam database mirrors
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: "DatabaseMirror {{ item }}"
    line: "DatabaseMirror {{ item }}"
  with_items: "{{ clamav_freshclam_databasemirrors }}"

- name: update freshclam http proxy server
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?HTTPProxyServer.*'
    line: "HTTPProxyServer {{ clamav_freshclam_httpproxyserver }}"
  when: clamav_freshclam_httpproxyserver

- name: disable freshclam http proxy server
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?HTTPProxyServer.*'
    line: "#HTTPProxyServer"
  when: not clamav_freshclam_httpproxyserver

- name: update freshclam http proxy port
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?HTTPProxyPort.*'
    line: "HTTPProxyPort {{ clamav_freshclam_httpproxyport }}"
  when: clamav_freshclam_httpproxyport

- name: disable freshclam http proxy port
  lineinfile:
    path: "{{ clamav_freshclam_conf_path }}"
    regex: '^#?HTTPProxyPort.*'
    line: "#HTTPProxyPort"
  when: not clamav_freshclam_httpproxyport

- name: create path to log file
  file:
    state: directory
    path: "{{ clamav_freshclam_updatelogfile | dirname }}"

- name: create log file
  file:
    state: touch
    owner: "{{ clamav_freshclam_databaseowner }}"
    path: "{{ clamav_freshclam_updatelogfile | dirname }}"


- name: enable freshclam
  systemd:
    name: clamav-freshclam
    state: started
    enabled: yes



...
