---
- name: install clamav
  package:
    name: clamav

- name: allow clam via selinux
  command: setsebool -P antivirus_can_scan_system  1
  when: ansible_os_family == 'RedHat'

- name: configure freshclam
  include_tasks: freshclam.yml

- name: configure clamscan
  include_tasks: clamav-daemon.yml


...
