---
- name: install clamav
  apt:
    name: clamav
  when:  ansible_pkg_mgr == 'apt'

- name: configure freshclam
  include_tasks: freshclam.yml

- name: boo hiss
  debug: 
    msg: whasssup

- name: configure clamscan
  include_tasks: clamav-daemon.yml


...
