---
- name: install aide
  package:
    name: aide

- name: configure aide for debian
  include_tasks: aide_debian_conf.yml
  when: "{{ ansible_os_family == 'Debian' }}"

- name: configure aide for redhat
  include_tasks: aide_redhat_conf.yml
  when: "{{ ansible_os_family == 'RedHat' }}"

...
