---
rsyslog_conf_path: /etc/rsyslog.d/60-ansible-default.conf
rsyslog_default_dest_path: /var/log/all.log #- is defaulted in template
rsyslog_default_dest_siem: No #use an @ for tcp
rsyslog_destinations:
- facility: '*'
  priority: '*'
  dest_path: "{{ rsyslog_default_dest_path }}"
  dest_siem: "{{ rsyslog_default_dest_siem }}"

rsyslog_actionfiledefaulttemplate: 'RSYSLOG_TraditionalFileFormat'
rsyslog_repeatedmsgreduction: 'on'
rsyslog_fileowner: "{% if ansible_os_family == 'RedHat' %}root{% elif ansible_os_family == 'Debian' %}syslog{% endif %}"
rsyslog_filegroup: "{% if ansible_os_family == 'RedHat' %}root{% elif ansible_os_family == 'Debian' %}adm{% endif %}"
rsyslog_filecreatemode: '0640'
rsyslog_dircreatemode: '0755'
rsyslog_umask: '0022'
rsyslog_privdroptouser: 'syslog'
rsyslog_privdroptogroup: 'syslog'

rsyslog_service_name: "{% if ansible_os_family == 'RedHat' %}rsyslog{% elif ansible_os_family == 'Debian' %}syslog{% endif %}"


...
