---
- hosts: all
  gather_facts: yes
  become: yes  
  tasks:
    


  roles:
  - role: git
    tags: git, never
  - role: syslogng
    tags: syslogng, never
  - role: splunkforwarder
    tags: splunkforwarder, never
  - role: nmap
    tags: nmap, never
  - role: ossechids
    tags: ossechids, never
    vars:
    - ossec_user_install_type: "local"
  - role: tiger
    tags: tiger, never
  - role: snort
    tags: snort, never
    #  - role: openvas
    #    tags: openvas, never #as in never, this is server software, not to be installed on endpoints
  - role: rsyslog
    tags: rsyslog, never
  - role: fail2ban
    tags: fail2ban, never
  - role: rkhunter
    tags: rkhunter, never
  - role: modsecurity
    tags: modsecurity, never
  - role: apparmor
    tags: apparmor, never
  - role: clamav
    tags: clamav, never
  - role: auditd
    tags: auditd, never
  - role: aide
    tags: aide, never
  - role: osquery
    tags: osquery, never


...
