---
- hosts: all
  gather_facts: yes
  become: yes  
  tasks:
    


  roles:
  - role: rsyslog
    tags: rsyslog
  - role: fail2ban
    tags: fail2ban, never
  - role: rkhunter
    tags: rkhunter, never
  - role: modsecurity
    tags: modsecurity, never
  - role: apparmor
    tags: apparmor, never
  - role: clamav
    tags: clamav, never
  - role: auditd
    tags: auditd, never
  - role: aide
    tags: aide, never
  - role: osquery
    tags: osquery, never


...
